# Generated by Django 2.2.12 on 2020-08-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('systolic', models.FloatField(blank=True)),
                ('diastolic', models.FloatField(blank=True)),
                ('pulse', models.IntegerField(blank=True)),
                ('recorded_at', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(blank=True)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_sugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('sugar', models.IntegerField(blank=True)),
                ('timeperiod', models.CharField(blank=True, max_length=100)),
                ('recorded_at', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diary_diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('meal', models.CharField(blank=True, max_length=100)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='diet/diet_%Y-%m-%d_%H:%M:%S')),
                ('image_count', models.IntegerField(blank=True)),
                ('lat', models.FloatField(blank=True, max_length=100)),
                ('lng', models.FloatField(blank=True, max_length=100)),
                ('recorded_at', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('weight', models.FloatField(blank=True)),
                ('body_fat', models.FloatField(blank=True)),
                ('bmi', models.FloatField(blank=True)),
                ('recorded_at', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
